# Generated by Django 4.2 on 2023-05-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodeapp', '0002_alter_qrcode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(upload_to='qr_codes/'),
        ),
    ]
